### ISSUE TITLE
Special characters in the storage path cause a white screen on Windows

### ISSUE THREAD

**Issue by Tombaaa** [iotaledger/firefly#1015]
## Issue description

special character in windows 10 user name and user directory (like ä in my case) prevent creating a firefly profile and token migration. Also for the creation of a firefly profile you only get a warning message - something went wrong - (see screenshot below) 
![image](https://user-images.githubusercontent.com/77152394/115851322-19e43c80-a427-11eb-9583-cd21933766e9.png)

## Wallet version

Firefly Version 1.0.0

## System specification

Windows 10

## Is it a repeatable issue?

Yes

## Steps To reproduce the issue

Explain how the maintainer can reproduce the issue.

1. start Firefly, select English, click and accept Privacy Policy 
2. select light/dark theme, continue, provide Profile Name (Tom), continue
3. then the windows "Something went wrong" appears in the right lower corner and disappears after 4 seconds
4. if you hit continue again, you can either create a new wallet or migrate or restore a wallet
5. in all cases you end up with a white screen, and nothing happens again at all

## Expected behaviour

Wallet should be created, Seed should be migrated

## Actual behaviour

White screen

## Errors

![image](https://user-images.githubusercontent.com/77152394/115852029-e9e96900-a427-11eb-9953-5da90aa0ebc0.png)

Error log: 
![image](https://user-images.githubusercontent.com/77152394/115852101-ff5e9300-a427-11eb-96da-4f1f15fffe54.png)

Diagnostic
![image](https://user-images.githubusercontent.com/77152394/115852154-0e454580-a428-11eb-9e5f-d061a12698b9.png)

Using a different user on the same computer but without special character did not trigger the issue, so it is assumed that the special character, in this case the ä, did trigger the error

By the way: Firefly 0.4.0 Beta worked with out any problems

**Comment by gguemues** [comment]
I have the same problem with win 10

Holen Sie sich Outlook für iOS<https://aka.ms/o0ukef>
________________________________
Von: Tombaaa ***@***.***>
Gesendet: Friday, April 23, 2021 11:39:26 AM
An: iotaledger/firefly ***@***.***>
Cc: Subscribed ***@***.***>
Betreff: [iotaledger/firefly] Can not create firefly profile - something went wrong - error message - special character in Windows 10 user name the likely cause (#1015)


Issue description

special character in windows 10 user name and user directory (like ä in my case) prevent creating a firefly profile and token migration. Also for the creation of a firefly profile you only get a warning message - something went wrong - (see screenshot below)
[image]<https://user-images.githubusercontent.com/77152394/115851322-19e43c80-a427-11eb-9583-cd21933766e9.png>

Wallet version

Firefly Version 1.0.0

System specification

Windows 10

Is it a repeatable issue?

Yes

Steps To reproduce the issue

Explain how the maintainer can reproduce the issue.

  1.  start Firefly, select English, click and accept Privacy Policy
  2.  select light/dark theme, continue, provide Profile Name (Tom), continue
  3.  then the windows "Something went wrong" appears in the right lower corner and disappears after 4 seconds
  4.  if you hit continue again, you can either create a new wallet or migrate or restore a wallet
  5.  in all cases you end up with a white screen, and nothing happens again at all

Expected behaviour

Wallet should be created, Seed should be migrated

Actual behaviour

White screen

Errors

[image]<https://user-images.githubusercontent.com/77152394/115852029-e9e96900-a427-11eb-9953-5da90aa0ebc0.png>

Error log:
[image]<https://user-images.githubusercontent.com/77152394/115852101-ff5e9300-a427-11eb-96da-4f1f15fffe54.png>

Diagnostic
[image]<https://user-images.githubusercontent.com/77152394/115852154-0e454580-a428-11eb-9e5f-d061a12698b9.png>

Using a different user on the same computer but without special character did not trigger the issue, so it is assumed that the special character, in this case the ä, did trigger the error

**Comment by Tombaaa** [comment]
@ gguemues, can you provide a printscreen from your diagnostics - left upper corner three bars, Firefly, Diagnostics. Thanks

**Comment by tolotos-rgu** [comment]
I have the same Problem:

Firefly v1.0.0
Plattform: win32
Plattformversion: 10.0.19041
Plattform-Architektur: x64
CPU-Anzahl: 4
Gesamtspeicher: 8142.9 MB
Freier Speicher: 3189.4 MB
Benutzerpfad: C:\Users\Rüdiger Gubler\AppData\Roaming\Firefly

**Comment by Tombaaa** [comment]
Thanks, so the ü. ä, ö characters are an issue in firefly

**Comment by tomecosta** [comment]
Issue still happening to me on the https://firefly.iota.org/ latest download

Error after introducing a name, White screen and freeze after SeedVault import.

**Comment by Grachas** [comment]
Check for updates show there is a new version but the version at the link still gives 1.0.0 instead of 1.1.0 currently.

**Comment by tomecosta** [comment]
> Check for updates show there is a new version but the version at the link still gives 1.0.0 instead of 1.1.0 currently.

@Grachas same issue happens to me, app indicates new version 1.1.0 on the web but if I download from the web it still is 1.0.0

**Comment by Tombaaa** [comment]
With Firefly 1.1.0 this issue is solved, finally was able to create a firefly profile and to migrate my tokens....
This issue is closed from my side! Thanks a lot IF

**Comment by tomecosta** [comment]
> With Firefly 1.1.0 this issue is solved, finally was able to create a firefly profile and to migrate my tokens....
> This issue is closed from my side! Thanks a lot IF

Thanks for sharing, but where is 1.1.0 available? On the official web there is just the 1.0.0 available. At the same time, on the Firefly app it says there is an update available that redirects to the 1.0.0 version download.

**Comment by Grachas** [comment]
Seems like 1.1.0 version is downloadable now from the official site.
