### ISSUE TITLE
Ask password to open Firefly wallet

### ISSUE THREAD

**Issue by Tobo01** [iotaledger/firefly#1020]
Ask user the password to open the Firefly wallet.

Right now, A user needs the pin to open each profile which is good. But when The user opens the Firefly wallet The user doesn’t need a password. I think it may be a good practice to ask the user to input a password to open the Firefly wallet.

**Comment by Amirmohsenkbit** [comment]
When importing syd81 digits, the wallet will not be displayed please help

**Comment by MiKeF05** [comment]
This is no issue because the PIN is designed to give you a quick access to your profile but you can´t do a transaction.

For a transaction you need to unlock your wallet with the password which unlocks stronghold. I think it would be a bad user experience to always use the password for a quick access.

**Comment by vbakke** [comment]
I agree with @MiKeF05. There is no need for a password to open the Firefly wallet. 

Optionally, one may, in a future release, make it configurable, if the user wants password protected the readonly part of the wallet.


I suggest: Won't fix.

**Comment by cvarley100** [comment]
Yeah the password is used for unlocking your funds and sending. The pin is used to block people from seeing your balance and transaction history. It is designed this way intentionally.
