### ISSUE TITLE
Migration to firefly

### ISSUE THREAD

**Issue by Mishell01** [iotaledger/firefly#1033]
Good afternoon, tell me, how long does the migration take in the firefly wallet? 10 hours of migration is already underway, is this normal?

**Comment by Travetown** [comment]
You can check in Trinity whether there is an outgoing transaction from your IOTA and your wallet is set to 0.  The outgoing transaction should begin on an address with TRANSFER ......  If this is the case, the migration is complete and you can exit Firefly.  If you then restart Firefly, you should see the migration in the transactions.  The balance itself is until April 28th.  0, because your IOTAs will not be available until tomorrow.

**Comment by Mishell01** [comment]
Yes, there are two outgoing transactions from Trinity, but the amount does not converge with the balance. In Trinity, the balance is 0

**Comment by Travetown** [comment]
Sorry, you will have to wait for someone else to answer you.  I don't know what to do now.  If you are in the Discord, ask there once.  # Firefly discussion

**Comment by Mishell01** [comment]
OK, the migration went well.

**Comment by VinceK7** [comment]
Hello there,
I experience an issue as well. Trinity recognizes the coins but when i try to migrate after a few minutes firefly pulls an error saying "There was an error migrating your funds. Please try again". I have tried 4-5 times in 2 days already and nothing happens. I also checked the Trinity if i have any pending transactions but nothing. My balance is still the same in Trinity. Anyone have any idea how to migrate? or i have to wait to do it after the 28th?

**Comment by Mishell01** [comment]
Hi, try to create a new sidevallet, maybe there were transactions, and the sidevallet was made before these transactions.

**Comment by VinceK7** [comment]
Hi Mishell01
I have not done any transactions from trinity since i transfered everything
there almost 2 years ago :) I did download firefly and when i install it i
created a new wallet by accident instead of use my old seed 🤦🏽‍♂️ Then
the balance of course was 0 and i was hmm how to transfer from trinity now
and then i watched the youtube video how to use my old seed and i was
dumbass i should do that instead of creating a new wallet :)))
So i follow the steps and thats how that error started popping. I teied it
few times , i also tried to reinstall firefly and its still the same. I
have the new wallet but thats is, and if i want to transfer the coins it
makes me create new 24 words everytime which is a lil annoying lol

You mean create a new wallet in firefly? and then how to transfer the cpins
to that wallet. im confused ?

**Comment by Mishell01** [comment]
Ask in Discord in # Firefly discussion, they will help.

**Comment by VinceK7** [comment]
Will do later . thank you

**Comment by MiKeF05** [comment]
I think this issue can be closed as the migration went well for the user who reported this issue. And other users can directly ask in Discord.

**Comment by VinceK7** [comment]
Yes, i did migrate successfully. Didnt loose anything.
Thank you

**Comment by MiKeF05** [comment]
Issue can be closed
