### ISSUE TITLE
Binance withdrawal issue.  

### ISSUE THREAD

**Issue by mikecamp8e11** [iotaledger/firefly#1157]
## Issue description

When withdrawing from Binance to my firefly wallet the following error comes up.  "The withdrawal address format is wrong.  Please check the withdrawal address length and character content and try again."

## Wallet version 1.1.0

Which version of wallet are you using?

- wallet version (version number, commit, or branch):

## System specification

What is your operating system? Windows 10

Mac/Win/Linux (+Version and or Distro if possible)

## Is it a repeatable issue?

Y/N

## Steps To reproduce the issue

Explain how the maintainer can reproduce the issue.

1.
2.
3.

## Expected behaviour

Describe what you expect to happen.

## Actual behaviour

Describe what actually happens.

## Errors

Paste any errors that you see from the Error Log in the Firefly menu or share screenshots of the issue.

**Comment by no8ody** [comment]
This is not a mistake on Firefly's part. Binance has not yet completed the conversion to Chrysalis, which is why the new address format is not recognized by Binance.
If you have questions or problems with Exchanges, it makes more sense to contact them directly, because no one from IF can help you here.
