### ISSUE TITLE
I can not enter my wallet. (No response, No error message, nothing.)

### ISSUE THREAD

**Issue by ahadis81** [iotaledger/firefly#1180]
The migration to Firefly wallet was successful. Before I was able to entry my wallet without any issue. 
Today I was trying to enter my wallet but after entering my 6 digits passcode, nothing happened. 
No response, No error message, nothing. 
What could be the problem and solution? 
Thanks.

**Comment by mazanyah** [comment]
I successfully migrated my tokens sometime ago from my Trinity Wallet. I have been able to access my Firefly Wallet since then. I have the most recent version of the Firefly Wallet: 1.1.0. The operating system is Windows 10. Today I was unable to access my Firefly Wallet using the 6 digit pin that I have successfully used on previous occasions to access my wallet. I am constantly getting the "1 incorrect attempt, 2 incorrect attempt, etc." Help please. Thank you.

**Comment by Col3Trickl3** [comment]
i'm in the same boat.  enter correct pin, then nothing happens.  lemme know when this is corrected.  it's a bullshit issue

**Comment by maxwellmattryan** [comment]
Hey,

It sounds like it is either locking up or maybe throwing an error silently in the back. Can you post a screenshot or copy / paste what it says in the error log (click on Firefly > Error log)? In the meantime have you found a workaround?

**Comment by mazanyah** [comment]
Windows 10 is presently not recognizing or allowing Firefly wallet (1.1.0) access via user’s previously confirmed PIN. It’s been that way for over 1 week (if not longer) as of today. Please resolve this issue. Thanks.

**Comment by ahadis81** [comment]
I updated the wallet (Firefly- Seach for updates- restart). Now I can see my tokens again.
________________________________

**Comment by ahadis81** [comment]
I updated the wallet (Firefly- Search for updates- restart Firefly). Now I can see my tokens again.
