### ISSUE TITLE
My iotas are not recognized (balance 0 Mi)

### ISSUE THREAD

**Issue by Andinuitis** [iotaledger/firefly#1389]
## Issue description

Hi guys,
I have a problem migrating with my Ledger Nano X. My iotas are not recognized (balance 0 Mi). In Trinity Wallet my balance is seen in index 4 and 5 on one address each (over 1Mi).
I updated Ledger Live, then installed both Iota Wallet on the Ledger. Installed Firefly 1.2.0 on my Win10. I am proceeding as described in the instructions.
Firefly was run as admin. 
empty error log
How can I proceed further?

## Wallet version

Iota Legacy 0.5.8
Iota 0.7.3
Firefly 1.2.0
Ledger Live 2.31.1

## System specification

Win 10 64 bit

## Is it a repeatable issue?

Y

**Comment by MiKeF05** [comment]
So you are in the migration process and can´t find your balance when you are searching for it? Does your ledger display "Generating adresses"? You can also visit the #help channel at IOTA Discord. You will get support there for your migration.

**Comment by begonaalvarezd** [comment]
@Andinuitis Did you try clicking the "Check Again" button in the balance screen a few times?

**Comment by jcdiaz** [comment]
@begonaalvarezd 
> Did you try clicking the "Check Again" button in the balance screen a few times?

The same thing happens to me and I tried to press more once the check button, always shows me the balance to 0 while in Trinity is correct

**Comment by begonaalvarezd** [comment]
@jcdiaz The check again button is more a "check further" rather than a "check again", so the more you press it, the further it searches. Can you please try clicking it couple of times? Some people in discord reported that they found their funds the ~10th time.

**Comment by jcdiaz** [comment]
I have pressed the button > 50 times and not get my balance, each time in the ledger is shown 3 times "Generating Address ..."

**Comment by MiKeF05** [comment]
@jcdiaz And you are sure the tokens are on your ledger? Do you use the correct ledger if you have more than one?

**Comment by Dsch00n** [comment]
@Andinuitis - I am having the same issue with Ledger Nano X. I know the Account Index I stored the balance on in Trinity. The Acocount Index is gibing me a 0 balance, even when checking multiple times. Any progress on your side and how can you still verify your balance with Trinity since it is phased out? 

Anyone any other suggestion?

**Comment by MiKeF05** [comment]
@Dsch00n Download the latest Trinity version and install it. Before you open it disable your internet connection and login to Trinity. Then go in Trinity to your account -> account management -> view seed. There you should see the used index for your ledger you need for the migration. 

You may need to click multiple times "check again" to search for your balance. And make sure your ledger displays "Generating Addresses". Otherwise your ledger doesn't search for the balance.

**Comment by Dsch00n** [comment]
Thanks @MiKeF05 for the instruction - though I had to re-install trinity. Hence I suppose the history is gone, is this correct and is there any other possibility to scan for the indexes?
