### ISSUE TITLE
Problem to import stronghold backup file

### ISSUE THREAD

**Issue by StCino** [iotaledger/firefly#1401]
## Issue description
I am not able to import a stronghold backup file in firefly 1.2.0 nor firefly 1.0

## Wallet version
Version 1.2.0
Version 1.0

## System specification
mac OS Big Sur 11.2.3 (20D91)
Windows 10

## Is it a repeatable issue?
Y

## Steps To reproduce the issue
1. Follow the process to import a stronghold backup file till you have to insert the password
2. Enter the password
3. click on "proceed" (Weiter)
4. Firefly accepted the password (because when I add a wrong one it complains)
5. Firefly is just idle for hours, the button is disabled, the back icon (arrow) is disabled

## Expected behaviour
1. To import the wallet

## Errors
No Errors show up

<img width="1267" alt="Bildschirmfoto 2021-08-14 um 10 07 03" src="https://user-images.githubusercontent.com/88925584/129439994-0e58bbaf-ef17-4a7d-90da-52a5951c8f1c.png">

**Comment by MiKeF05** [comment]
Try to uninstall Firefly and delete the following folder:

Windows: C:\Users\[username]\AppData\Roaming\Firefly
Mac: ~/Library/Application Support/Firefly

Then install Firefly again and try to import your Stronghold backup file. Make sure to have the 24 words passphrase of each of your profiles or a stronghold backup file.

**Comment by odjones** [comment]
I have repeated this bug (twice) on a new, freshly-installed notebook with Windows 10. No other software ever installed, only a fresh install of Windows 10 64-bit (version 19043.1237). First time with a run of O&O ShutUp10 with recommended options to stop keylogging, et cetera, and the second time with another fresh reinstall of Windows 10 (same version, following a disk wipe) and application of all Windows updates, then installing Firefly 1.2.0, without O&O ShutUp10 being run (not my ideal choice, but necessary to eliminate O&O ShutUp10 as a potential cause.)

Stronghold backup file is on a write-protected USB stick. Password is accepted, but nothing happens when I click "Continue".

Firefly just hangs at that point: 0% CPU activity. 0% network activity. 0% disk activity, according to the task monitor.

I have tried the workaround, completely removing %USERNAME%\AppData\Roaming\Firefly after removing Firefly, then reinstalling Firefly, to no avail. Import functionality is not available.

I would regard this as a pretty major bug, and I don't know why it has still not yet been fixed, some six weeks later.

Fix it ASAP, please.
