### ISSUE TITLE
Missing transaction in transaction history

### ISSUE THREAD

**Issue by MiKeF05** [iotaledger/firefly#1441]
### Issue description

A user reported a missing transaction in the transaction history. (Discord message https://discord.com/channels/397872799483428865/748265907351978115/883672275818250310) A transaction was made from wallet 1 to wallet 2 inside one ledger profile. The transaction appears in the transaction history of wallet 2 but is missing in the overall history of the profile and in wallet 1. Here are the images provided from the user:

![Bildschirmfoto_2021-09-04_um_13 29 20](https://user-images.githubusercontent.com/71659397/132093614-4739db3d-a955-49ea-8b7f-e2ee75ac48d0.png)
![Bildschirmfoto_2021-09-04_um_13 29 36](https://user-images.githubusercontent.com/71659397/132093616-fdd9ce3e-760c-49a5-8e3e-a3830a6a6023.png)

The user also made an internal transfer from wallet 1 to wallet 1 where the symbol in the transaction history is wrong. See second image "Empfangen" at 14:29. This should be an incoming transaction and the other symbol.

### Firefly version

1.2

### OS details

macOS HIgh Sierra Version 10.13.6

### Can the issue be reliably reproduced?

No

### Steps to reproduce the issue

1.
2.
3.
...

### Expected behaviour

The transaction from wallet 1 to wallet 2 should also appear as outgoing in wallet 1. 

### Actual behaviour

At the moment it is only incoming in wallet 2.

### Errors

![Bildschirmfoto_2021-09-04_um_14 30 57](https://user-images.githubusercontent.com/71659397/132094529-96f288d1-2f58-40e7-b236-50909686152f.png)

**Comment by sidney66six** [comment]
I got same issue here with below info:
Firefly version
1.2

OS details
18.04.1-Ubuntu X86
Firefly v1.2.0
Language: en
Currency: USD
Node settings: Automatic node selection
Platform: linux
Platform Version: 5.4.0-81-generic
Platform Architecture: x64
CPU Count: 8
Total Memory: 7927.1 MB
Free Memory: 961.9 MB
User Path: /home/ubuntu/*****

Can the issue be reliably reproduced?
Not sure.

Steps to reproduce the issue( not sure if it can be reproduce)
1.update from firefly v1.1.0 to v1.2.0
2. receive 1st transaction.

Expected behavior
The transaction history and profile history should not disappear.

Actual behavior
before 
![image](https://user-images.githubusercontent.com/13897185/132690200-e424697e-3e65-4e82-97cc-3d7081b64f0c.png)

after
![image](https://user-images.githubusercontent.com/13897185/132689512-349229d3-afbe-4f9b-aaae-0ac9a0ed7381.png)

The transaction history and profile history disappear.


Errors
Thu, 09 Sep 2021 11:36:37 GMT
ClientError: {}

Thu, 09 Sep 2021 10:59:10 GMT
StrongholdError: `failed to perform action: `Engine Error: Crypto Error: `error in algorithm XCHACHA20-POLY1305`, Unable to read snapshot. Please try another password.``

Thu, 09 Sep 2021 10:59:09 GMT
StrongholdError: `failed to perform action: `Engine Error: Crypto Error: `error in algorithm XCHACHA20-POLY1305`, Unable to read snapshot. Please try another password.``

Thu, 09 Sep 2021 10:58:43 GMT
StrongholdError: `failed to perform action: `Engine Error: Crypto Error: `error in algorithm XCHACHA20-POLY1305`, Unable to read snapshot. Please try another password.``

**Comment by emilio811** [comment]
Hi, I have the same issue and no body is going to tell us anything.

**Comment by steffenroeber** [comment]
I have same issue (1.3.0), after recovering an accoutn due to #1683.
No transaction history for any of the recovered accounts is available.
Transaction  history is completetly empty.

**Comment by MiKeF05** [comment]
If you use the 24 words phrase to restore your transaction history it will most likely be emtpy as the history can't be saved with the 24 words. If you also want to restore your transaction history you need to restore it with the stronghold backup + password.
