### ISSUE TITLE
Pin change causes the issues with connection and profile state

### ISSUE THREAD

**Issue by brad15000** [iotaledger/firefly#1656]
### Issue description

i modify the pasword and pin and put a new password and pin and the next restart of pc y found that The balance is 0 and there is no wallets.
There isn't also connection.
Thanks for the help.

### Firefly version

version 1.2.0

### OS details

windows 10 pro

### Can the issue be reliably reproduced?

Yes

### Steps to reproduce the issue

1.
2.
3.
...
i dont know

### Expected behaviour

i dont know

### Actual behaviour

i expect it can be fixed

### Errors

i dont know

**Comment by MiKeF05** [comment]
This is a known bug and will hopefully be fixed with the new version. In the meantime you can try to create a new profile and restore your wallet with the 24 words or the stronghold file.

**Comment by nicole-obrien** [comment]
Thanks just to add further info for debugging: this only happens once firefly is closed and reopened. Initially after change, logout and log back in the profile is fine.

**Comment by nicole-obrien** [comment]
I believe we have found the issue in the wallet.rs library. Once that dependency is fixed we can update our dependency and close this issue.

**Comment by nicole-obrien** [comment]
PR on wallet.rs repo: https://github.com/iotaledger/wallet.rs/pull/822

**Comment by nicole-obrien** [comment]
Another PR on wallet.rs repo to fix this even more: https://github.com/iotaledger/wallet.rs/pull/837

**Comment by CryptoDani28** [comment]
**Issue description**

The same problem just happened to me. I changed my pin and now I cant lock in anymore. After I enter the pin, it accepts it but it never finished loading (see the picture). If I enter a wrong pin, it says the pin is wrong.
Firefly version 1.3.2
windows 10 

**Can the issue be reliably reproduced?**
Yes

**Steps to reproduce the issue**

1. I open Firefly
2. I enter the new pin
3. the "loading-screen" opens and then nothing happens


**Expected behaviour**

I should be able to logg in.

Actual behaviour

I cann not log in

Errors

i dont know
![Firefly fehler](https://user-images.githubusercontent.com/98235712/150654231-cf591832-6b47-4fd6-9f54-4e5bfc5d9471.JPG)
w

**Comment by CryptoDani28** [comment]
I solved the problem with the steps described in #2131
