### ISSUE TITLE
Transactions FireFly wallet

### ISSUE THREAD

**Issue by bssenkel** [iotaledger/firefly#1854]
### Issue description

Hi, under the menu "latest transactions" in the firefly wallet i have 2 transactions with grey background. Before this happened, i tried to start staking.
Now, nothing happens and i can not start staking. But i have no problem with the nodes.
Is it because of the overloaded network?  I have the problem since yesterday. 
Sorry, but i posted my problem under "discussions", too. But i am afraid, i could loose my tokens.

Kind regard
Stefan
![foto](https://user-images.githubusercontent.com/96527786/147102282-57a20038-e7e8-4571-af6f-706db05f33a8.JPG)

### Firefly version

1.3.0

### OS details

Windows 10

### Can the issue be reliably reproduced?

No

### Steps to reproduce the issue

1.---?---
2.
3.
...

### Expected behaviour

please solve my problem

### Actual behaviour

??

**Comment by nicole-obrien** [comment]
When you originally tried to stake, the nodes must have been crashing and did not process this staking message to add it to the tangle. Firefly still thinks that this is a pending message as it has not received a response from the node. The nodes must have cleared their message queue and since restarting they don't know this message exists.

Creating a new profile with same seed, the pending message will not exist so firefly is not waiting for a response, and you can freely issue a staking transaction to the now working nodes.

**Comment by bssenkel** [comment]
Thank you very much, now it works.

**Comment by MiKeF05** [comment]
Okay great. Issue can be closed
