### ISSUE TITLE
Unvalid receiver adress genrated within Firefly

### ISSUE THREAD

**Issue by MrPassman** [iotaledger/firefly#1875]
### Issue description

The provided/generated receiver adress of my wallet within Firefly seems to be an unvalid adress. 
As soon as I copy the receiver adress of my wallet within Firefly and paste this adress in Bitpanda to send Iota, Bitpanda declares the adress as unvalid.

### Firefly version

3.1.0

### OS details

Windows 10

### Can the issue be reliably reproduced?

Yes

### Steps to reproduce the issue

1. Copy receiver adress from Wallet ("atoi1qqjd20lfzecjwsqt3vuztfe4d0hp064hrn70um3fvcmxqhv66kq7zv7hc0s")
2. Paste copied adress in Bitpanda to send iota to this adress
3. In Bitpanda, adress is declared as no valid adress
...

### Expected behaviour

Adress is valid. Coins can be sent to this adress.

### Actual behaviour

Not possible to send coins to the generated adress of my personal wallet

### Errors

There is no error report within Firefly.

**Comment by t00k** [comment]
You have created a developer profile.
During profile creation you clicked the checkbox for "Developer profile" which enables a developer profile, only connected to the IOTA testnet.

Log out, create a new profile, and do NOT click the "Developer profile" checkbox during profile creation. This new seed (back it up accordingly) will give you "iota1"-address instead of atoi.

**Comment by r-c-k** [comment]
When setting up your profile, you selected „Developer profile“. This will connect you to the devnet and will generate devnet addresses.

Set up a new profile without ticking the „Developer profile“ checkbox.
