### ISSUE TITLE
我的FIREFLY錢包地址無法收款

### ISSUE THREAD

**Issue by JACKFIREFLY3** [iotaledger/firefly#1897]
### Issue description

atoi1qpaxxfagwejxzs0qg247svlm0gpd4ftmwywqfkpqu7sz9aleyzfwx0ya3ac
我的錢包地址長這樣
不能收IOTA
要如何解決

### Firefly version

1.3.0

### OS details

Windows 10

### Can the issue be reliably reproduced?

Yes

### Steps to reproduce the issue

照步驟來~沒辦法收款

### Expected behaviour

幫我解決讓我能明日前收款成功我要質押

### Actual behaviour

沒辦法收款IOTA

### Errors

atoi1qpaxxfagwejxzs0qg247svlm0gpd4ftmwywqfkpqu7sz9aleyzfwx0ya3ac

為什麼我最前面不是iota

**Comment by JACKFIREFLY3** [comment]
> ### Issue description
> atoi1qpaxxfagwejxzs0qg247svlm0gpd4ftmwywqfkpqu7sz9aleyzfwx0ya3ac 我的錢包地址長這樣 不能收IOTA 要如何解決
> 
> ### Firefly version
> 1.3.0
> 
> ### OS details
> Windows 10
> 
> ### Can the issue be reliably reproduced?
> Yes
> 
> ### Steps to reproduce the issue
> 照步驟來~沒辦法收款
> 
> ### Expected behaviour
> 幫我解決讓我能明日前收款成功我要質押
> 
> ### Actual behaviour
> 沒辦法收款IOTA
> 
> ### Errors
> atoi1qpaxxfagwejxzs0qg247svlm0gpd4ftmwywqfkpqu7sz9aleyzfwx0ya3ac
> 
> 為什麼我最前面不是iota
![1640584095864](https://user-images.githubusercontent.com/96711259/147439211-51281f8e-18df-4748-b6c1-4d8eb10e692f.jpg)

**Comment by Billy4195** [comment]
Hi,

You can create a new config without using a developer profile.
> 請你左下角按登出  "添加個人檔案" > 開發者設定檔的選項不要勾選  創立好的錢包位址開頭應該就是iota了

**Comment by t00k** [comment]
Do not use developer profiles in the Firefly Wallet if you are not a Developer. A developer Profile will connect you to the Testnet and generate addresses that do not work on IOTA Mainnet. These testnet addresses start with "atoi1" instead of the mainnet addresses "iota1".
If you have accidentally created a developer profile and did send funds to an "atoi1" address you have not lost your funds. 
To make these funds accessible you need to use the "recover a wallet" function in Firefly while creating a new profile. 
Create a "non developer" profile and use the 24 words that you have saved from your "developer profile" to restore this new profile (non developer).
Your funds will show up in this new profile.

**Comment by JACKFIREFLY3** [comment]
非常感謝回答的各位大大~解決這個蠢問題了~^^

**Comment by MiKeF05** [comment]
Issue can be closed
