### ISSUE TITLE
adding network

### ISSUE THREAD

**Issue by Olatuyitony347** [iotaledger/firefly#1922]
am unable to add node network or connect with the current one to activate staking of MIOTA
kindly help me wih the issue as soon as possible

**Comment by t00k** [comment]
If you are using a Developer profile and are connected to the "Chrysalis testnet" do this;
Do not use developer profiles in the Firefly Wallet if you are not a Developer. A developer Profile will connect you to the Testnet and generate addresses that do not work on IOTA Mainnet. These testnet addresses start with "atoi1" instead of the mainnet addresses "iota1".
If you have accidentally created a developer profile and did send funds to an "atoi1" address you have not lost your funds. 
To make these funds accessible you need to use the "recover a wallet" function in Firefly while creating a new profile. 
Create a "non developer" profile and use the 24 words that you have saved from your "developer profile" to restore this new profile (non developer).
Your funds will show up in this new profile.

If you only have issues with the mainnet network, change node by doing the following;
Settings -> Network config -> Manual -> add https://mainnet-node.tanglebay.com/ as a node and set it as primary.

**Comment by Olatuyitony347** [comment]
Am having issue with mainnet not developer testnet,I can't add the network
![Uploading IMG_20211228_122035_757.jpg…]()

**Comment by Olatuyitony347** [comment]
Anything I want to change node it will tell me something went wrong

**Comment by t00k** [comment]
Are you trying to migrate?
If so, download the 1.2.0 version and use that.

also can you check menu -> firefly -> error log and see what errors you have?

cannot see the screenshot.

**Comment by Olatuyitony347** [comment]
![IMG_20211228_123349_570](https://user-images.githubusercontent.com/86169011/147571625-684aa0cc-6616-432a-8f91-fa650aafe07d.jpg)
![IMG_20211228_122035_757](https://user-images.githubusercontent.com/86169011/147571675-1f2dac1e-1c58-4b59-ac2e-aa72bc43cde0.jpg)

**Comment by Olatuyitony347** [comment]
Am not trying to migrate am trying to add the network node: 
https://mainnet-node.tanglebay.com/ but I always received this error message: SOMETHING WENT WRONG 
And the error I sent the screenshot above

**Comment by t00k** [comment]
Hmm, are you using a work PC or maybe a PC with some strict firewall/VPN?

Looks like it is not allowing outgoing calls.

**Comment by Olatuyitony347** [comment]
Please how can I disable that

**Comment by Olatuyitony347** [comment]
How is node network connected with outgoing calls boss?

**Comment by Olatuyitony347** [comment]
Not allowing outgoing calls is that the issue

**Comment by MiKeF05** [comment]
Yes. You need to make sure that you have a proper connection to the node

**Comment by Olatuyitony347** [comment]
Can you please help me with at least the correct settings of firewall

**Comment by MiKeF05** [comment]
I´m sorry but I don´t know which firewall you have.

**Comment by Olatuyitony347** [comment]
What other software should I disable for me to be able to stop receiving "something went wrong"  if I want to add node

**Comment by Olatuyitony347** [comment]
Aside from firewall

**Comment by MiKeF05** [comment]
Antivirus

**Comment by Olatuyitony347** [comment]
Ok but I don't use antivirus
Any other one

**Comment by MiKeF05** [comment]
Please join the IOTA Discord server (https://discord.iota.org/) and go to the #help channel. Otherwise it would be difficult to help you with this issue.

**Comment by Olatuyitony347** [comment]
I can't join discord it keeps telling me am using vpn and vpn is not
allowed there
And I did not use vpn

**Comment by Olatuyitony347** [comment]
Everything about this project AIRDROP is so stressful

**Comment by MiKeF05** [comment]
Something with your internet connection is really weird. You need to figure this out. But I can´t help you with this issue as it is not related to Firefly.

**Comment by rajivshah3** [comment]
@Olatuyitony347 what is your Discord username?

**Comment by Olatuyitony347** [comment]
@rajivshah3  Olatuyitony347#0136 is my discord username

**Comment by giorgica** [comment]
Hi . i have the same problem. giorgica#3883 discord username.
maybe you can olso help me.

**Comment by rajivshah3** [comment]
@Olatuyitony347 fixed ✅ 
@giorgica can you please try rejoining again and then make sure you respond to the DM from the bot?

**Comment by MiKeF05** [comment]
@rajivshah3 What was the issue for Olatuyitony?

**Comment by rajivshah3** [comment]
Ah I probably should have clarified — he's able to access the Discord server now. The bot was blocking him for some reason

**Comment by giorgica** [comment]
i am here. i dont have message on discord

**Comment by rajivshah3** [comment]
@giorgica please try rejoining the Discord server by clicking [here](https://discord.iota.org)

**Comment by cvarley100** [comment]
Duplicate issue.
