### ISSUE TITLE
Migration problem with DEV-Profil

### ISSUE THREAD

**Issue by qYamakasip** [iotaledger/firefly#1983]
### Issue description

Hi.
I'm trying to migrate my Iota from IOTA Light Wallet 2.5.7. 
After the migration I realized that I had created a developer profile. The IOTA are not available as credits.
The latest transaction is an entry "Fund migration 28 Dez 2021" and i get the message 
"Your funds will become availiable shortly". What do I have to do to get my iota back?

Any advice would be greatly appreciated.
Thank you!

### Firefly version

1.3.0

### OS details

Windows 7

### Can the issue be reliably reproduced?

No

### Steps to reproduce the issue

1.Create a Developer Profil
2.Migrate IOTA from Light Wallet 2.5.7.
3.
...

### Expected behaviour

I get the Iota on my wallet.

### Actual behaviour

I am waiting for the fund

### Errors

Tue, 28 Dec 2021 21:25:02 GMT
LatestAccountIsEmpty: can't create accounts when the latest account doesn't have message history and balance

Tue, 28 Dec 2021 21:24:54 GMT
LatestAccountIsEmpty: can't create accounts when the latest account doesn't have message history and balance

Tue, 28 Dec 2021 19:12:42 GMT
StrongholdError: `failed to perform action: `Engine Error: Crypto Error: `error in algorithm XCHACHA20-POLY1305`, Unable to read snapshot. Please try another password.``

**Comment by t00k** [comment]
Log out of the developer profile and create a new profile without the developer modus activated.

If you have accidentally created a developer profile and did send funds to an "atoi1" address you have not lost your funds. 
To make these funds accessible you need to use the "recover a wallet" function in Firefly while creating a new profile. 
Create a "non-developer" profile and use the 24 words that you have saved from your "developer profile" to restore this new profile (non-developer).
Your funds will show up in this new profile.

Also, please update from Windows 7 since this is not supported anymore.

**Comment by qYamakasip** [comment]
Hi there,

thank you very much for the quick help. The bug was fixed with their instructions.

**Comment by t00k** [comment]
Glad to hear! Please mark this issue as solved and close it :)
