### ISSUE TITLE
Error en dirección de cartera

### ISSUE THREAD

**Issue by Sertx19** [iotaledger/firefly#1984]
### Issue description

Quiero depositar mis IOTAs en mi cartera de Firefly, el problema es que mi dirección aparece como " atoi1qrmyxdmpdqaqhull2twemqghtyqe22s4dvamvkksx20295c24559jjkp753 " , apareciendo las 4 primeras letras "atoi" en vez de "iota", por lo que no se me permite realizar ningún deposito dándome como razón que el formato de mi dirección no es válido. En cambio si cambio las 4 letras y escribo manualmente " iota1qrmyxdmpdqaqhull2twemqghtyqe22s4dvamvkksx20295c24559jjkp753 " si que me permite realizar el deposito. Mi duda es si al efectuar el retiro con esta última dirección, se depositaría a mi cartera o no.
 Gracias de antemano

### Firefly version

1.3.0

### OS details

Windows 10 Home 21H1

### Can the issue be reliably reproduced?

No

### Steps to reproduce the issue

1.
2.
3.
...

### Expected behaviour

Esperaba poder depositar mis IOTA sin problema colocando mi dirección de la cartera.

### Actual behaviour

Al escanear o colocar mi dirección de cartera aparece el siguiente mensaje : Por favor, introduce una dirección válida. Verifica la longitud de la dirección de retiro y el contenido de los caracteres, e inténtalo de nuevo.
Sólo me deja continuar si cambio las 4 primeras letras de "atoi"  a "iota".

**Comment by MiKeF05** [comment]
You are using the developer profile and are connected to the testnet. Please create a new profile and DO NOT check the developer profile.

**Comment by t00k** [comment]
Do not use developer profiles in the Firefly Wallet if you are not a Developer. A developer Profile will connect you to the Testnet and generate addresses that do not work on IOTA Mainnet. These testnet addresses start with "atoi1" instead of the mainnet addresses "iota1".
You need an address from a normal profile to withdraw IOTA tokens from exchanges. These addresses start with "iota1........".
Log out of the developer profile and create a new profile without the developer modus activated.

If you have accidentally created a developer profile and did send funds to an "atoi1" address you have not lost your funds. 
To make these funds accessible you need to use the "recover a wallet" function in Firefly while creating a new profile. 
Create a "non-developer" profile and use the 24 words that you have saved from your "developer profile" to restore this new profile (non-developer).
Your funds will show up in this new profile.

**Comment by Sertx19** [comment]
Muchas gracias por vuestra colaboración, gracias a vuestras indicaciones he conseguido hacerlo correctamente.
