### ISSUE TITLE
my iota tokens are not appear on the wallet

### ISSUE THREAD

**Issue by faroukomar** [iotaledger/firefly#2004]
Dear team 

request your assistance, i have transferred my iota rom binance ex to my firefly wallet for more than 2 days now
still the balance is not appear on the wallet, once i did the transferred the wallet was not connected and i dont know what has went wrong, now i have restore my wallet on another laptop , status has been changed to connected but the balance still  0

please note that the balance has been taking and transaction confirmed from binance  

this is my firefly address: 
atoi1qqhnmkqf9498ckzjdk48c45f4t5w2lvjvlneurp8d8unyv8mnuvy7zhk2tv

Please do the needful and thanks in advance for all the support 

waiting to hear from you 

Best Regards

**Comment by t00k** [comment]
Do not use developer profiles in the Firefly Wallet if you are not a Developer. A developer Profile will connect you to the Testnet and generate addresses that do not work on IOTA Mainnet. These testnet addresses start with "atoi1" instead of the mainnet addresses "iota1".
You need an address from a normal profile to withdraw IOTA tokens from exchanges. These addresses start with "iota1........".
Log out of the developer profile and create a new profile without the developer modus activated.

If you have accidentally created a developer profile and did send funds to an "atoi1" address you have not lost your funds. 
To make these funds accessible you need to use the "recover a wallet" function in Firefly while creating a new profile. 
Create a "non-developer" profile and use the 24 words that you have saved from your "developer profile" to restore this new profile (non-developer).
Your funds will show up in this new profile.
