### ISSUE TITLE
[Task]: Improve mobile developer setup steps 

### ISSUE THREAD

**Issue by maxwellmattryan** [iotaledger/firefly#2523]
### Task description

When setting up the mobile dev environment, there are lots of questions like what OS to use, if / how to emulate said OS, best practices and tips, setting up android studio with Capacitor, etc. The goal of this task is to eliminate as many questions as possible in this process.

### Requirements

_TBD_

### Acceptance criteria

Meets the above (TBD) requirements.

### Creation checklist

- [X] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project

**Comment by rajivshah3** [comment]
[Capacitor's documentation](https://capacitorjs.com/docs/getting-started/environment-setup) seems like a good start. Java would be necessary if people want to use the command line instead of Android Studio (IIRC Android Studio ships with Java built-in). The CocoaPods installation implies that Ruby is installed, but macOS ships with an older version of Ruby anyway. I'm not sure if we need anything else besides the dependencies listed there and the required dependencies for building the backend (basically everything listed in [the desktop README](https://github.com/iotaledger/firefly/blob/2055324a4ba8e0c86c6e2d74685e8a09d1112167/packages/desktop/README.md) besides some of the Linux-specific dependencies).
