### ISSUE TITLE
[Bug report]: Balance not updating without Ledger

### ISSUE THREAD

**Issue by trimat1** [iotaledger/firefly#2893]
### Platform

Desktop

### Version

1.4.1

### Description

Firefly doesn´t update balance of ledger profile.

### Expected behaviour

For the addresses already known by firefly the wallet should update the balance according to tangle.
(ofc it can´t create new addresses without ledger)
Ledger should imho be as less as possible connected to the PC - normally it´s stored somewhere - and definitly not for just updating the balance on already known addresses.

### Actual behaviour

Doesn´t auto update.
When pressing update button -> Message no Device recognized

### Can the issue reliably be reproduced?

Yes

### Steps to reproduce the issue

1. Have Ledger Wallet with already received coins.
2. Use same address to send coins to
3. checking in firefly if coins received (doesn´t work when Ledger not connected)

### Operating System

Windows

### Developer Profile

No

### Profile Type

Hardware (Ledger)

### Staking

Previously staked

### Crash Status

None of the above

### Duplicate declaration

- [X] I have searched the issues tracker this issue and there is none

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by maxwellmattryan** [comment]
Hey @trimat1, we're planning on moving to a single address strategy soon. With that, it will be easier to stow away the Ledger device since we only worry about one address to search for a balance on whereas now we have to consider an arbitrary number of addresses where the funds may be (somewhat better for privacy, but not really).
