### ISSUE TITLE
[Task]: Responsive addresses for smaller screen sizes

### ISSUE THREAD

**Issue by paul-boegelsack** [iotaledger/firefly#3521]
### Task description

For some screen sizes the address length is too long to display the complete string. Addresses have to be displayed in a responsive way, when this happens. For example with a certain number of start and end digits visible: **iot1qasd131a....ck8a0sl**

### Requirements

Implement a way to display an address responsively

### Acceptance criteria

Can be closed when the requirements are fulfilled.

### Creation checklist

- [x] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project

**Comment by paul-boegelsack** [comment]
@amadeu2 Moved this task to todo because it is related to the feedback card in the trello fixed column.

**Comment by begonaalvarezd** [comment]
@amadeu2 Is this something we really want to do? 

In my opinion hiding characters from an address in the send flow isnt a great idea. If the input is too small we should provide a way for the user to be able to check easily if the address is correct, instead of hiding it? One character wrong and you could be sending your funds somewhere else 🙈

**Comment by amadeu2** [comment]
Thanks @begonaalvarezd! I fully agree with you, we should discuss it better with the UX team before merge it.
