### ISSUE TITLE
[Task]: Apply profile folder name changes to mobile

### ISSUE THREAD

**Issue by begonaalvarezd** [iotaledger/firefly#3802]
### Task description

In desktop there was a refactor that stores the profiles under folders with a hash as name, not the profile name anymore. 
In mobile this isnt implemented.

In mobile when you rename a profile, the old system is implemented, and that leads to the app doing a logout. If we apply these changes, we might also fix the logout issue on profile name change

### Requirements

TBD

### Acceptance criteria

TBD

### Creation checklist

- [ ] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project

**Comment by jeeanribeiro** [comment]
The profiles are implemented with hash in mobile also, I checked by debugging in Android Studio the device file explorer has the `__storage__` folder with a hash folder for each profile, I'm investigating for the root cause of the logout when changing profile name, which is not related to the folder name
