### ISSUE TITLE
[Task]: fix decimal not possible to enter in iOS

### ISSUE THREAD

**Issue by begonaalvarezd** [iotaledger/firefly#4379]
https://discord.com/channels/397872799483428865/996835547484004454/1014567879842218066

**Comment by jeeanribeiro** [comment]
The decimal separator in keyboard is related to the user's locale.
The keyboard don't had decimal separator before adding the inputmode attribute in input element.
Don't know if it is possible to maintain numpad keyboard with a decimal separator that is not the default from the user's locale, maybe it would need native code

https://developer.apple.com/forums/thread/127722

**Comment by amadeu2** [comment]
I've tried to fix it without success 😢 seems it happens when you have a different region, in my case Argentina, with English defined as main OS language. Then I've changed the region to US and it works because the OS language is paired with the Webview language.

Maybe we could use the `getLanguageTag()` method from Capacitor Device plugin, but we should wait for the v4 update: https://capacitorjs.com/docs/apis/device#getlanguagetag
to get the region and deduce the decimal char from there.

**Comment by paul-boegelsack** [comment]
As far as I can see the input component line 55 prevents the wrong decimal sign from being set, right? I don't know if this is the best workaround right now but I tested to set the right sign instead of nothing. I tried 
`value += decimalSeparator` before the `e.preventDefault()` but something changes the input back to the opposite. Dot becomes comma and vice versa. Any ideas?

**Comment by amadeu2** [comment]
yes @paul-boegelsack maybe that could work, or to fix on JS side only. As iOS has only one decimal char to tap: `,` or `.` maybe we can detect the input char and set the `decimalSeparator` with that value

**Comment by amadeu2** [comment]
I've just read this https://github.com/iotaledger/firefly/issues/4393 💪
I think it's completely related with this task
