### ISSUE TITLE
[Subtask]: Fix spacing of onboarding layout

### ISSUE THREAD

**Issue by nicole-obrien** [iotaledger/firefly#4439]
![Frame 6276](https://user-images.githubusercontent.com/89913787/188306237-baadd91a-f3bb-44c7-8ea9-e5fb085f22cd.png)

**Comment by MarkNerdi** [comment]
I think the problem lies on macOS. On linux the spacing is correct, but it seems like for macOs we don't define the safearea correctly. How does the rest of the app look like regarding the top margin/padding?


![Screenshot-157](https://user-images.githubusercontent.com/105642810/189073641-1eaea547-e090-4ef0-af5e-8b828fc45fbb.png)
