### ISSUE TITLE
[Bug report]: Claimed rewards show actual balance instead of claimed rewards

### ISSUE THREAD

**Issue by Tuditi** [iotaledger/firefly#4564]
### Platform

Desktop

### Version

stardust-develop

### Description

When claiming rewards with ledger, it shows the balance of the account instead of the originally claimed amount.

### Expected behaviour

Show originally claimed rewards, if rewards have been already claimed

### Actual behaviour

Shows the balance of the account.

I claimed 1000 SMR, sent 12 away and started to claim rewards with the same ledger device again.

![image](https://user-images.githubusercontent.com/45079109/190613235-e1331b54-76ff-4f42-b1bf-9d03a4d53abd.png)

### Can the issue reliably be reproduced?

Yes

### Steps to reproduce the issue

1. Claim `X` rewards with a fresh ledger account
2. Create an account and send `Y` amount of SMR to another account
3. Logout and restart the claiming process with the same ledger device
4. Claim rewards
5. Witness that claimed amount is `X-Y`

### Operating System

Linux

### Developer Profile

Yes

### Profile Type

Hardware (Ledger)

### Crash Status

None of the above

### Error Messages

None

### Error Logs

```shell
None
```

### Duplicate declaration

- [X] I have searched the issues tracker this issue and there is none

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by maxwellmattryan** [comment]
While this is technically true, some thoughts about the problem:
- The claiming transactions themselves look like any other basic transaction from one SMR address to another, so there's nothing unique or deducible about them that would help here. We'd need extra logic to search the IOTA-derived Ed25519 addresses in whatever history is available for the SMR-derived addresses
- Most users will only use this once _and_ they (likely) won't have any funds at that time (this is technically an assumption, but I feel confident this is the case). If they withdrew funds from an exchange, then these would get picked up here, but otherwise in most cases it should show that they haven't claimed funds at all. 

I think this should be considered "low" priority and something we can try and work in if there is time for it this week.

**Comment by nicole-obrien** [comment]
I don't think we need to handle this, its very unlikely for users to partially claim, receive funds from somewhere and then go through the claiming flow again. For all intents and purpose the claimed is just the balance on the shimmer account.
