### ISSUE TITLE
[Bug report]: Ubuntu 18.04. white screen

### ISSUE THREAD

**Issue by Romano125** [iotaledger/firefly#4776]
### Platform

Desktop

### Version

2.0.0

### Description

When i start my Firefly Shimmer i can see only white screen and none of the options inside the app works. I can only open about shimmer window and that one shows about.

### Expected behaviour

To see UI of Firefly Shimmer app

### Actual behaviour

White screen

### Can the issue reliably be reproduced?

No

### Operating System

Linux

### Developer Profile

No

### Profile Type

Software (Stronghold)

### Staking

Actively staking

### Crash Status

White screen

### Error Logs

```
"Error: node-loader:
Error: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /tmp/.org.chromium.Chromium.vMz2YI)", source: node:electron/js2c/renderer_init (73)
[9613:0930/104420.282165:INFO:CONSOLE(2)] "Uncaught TypeError: Cannot read properties of undefined (reading 'BarcodeManager')", source: file:///tmp/.mount_fireflrE5vM4/resources/app.asar/public/build/index.js (2)
```

### Duplicate declaration

- [X] I have searched the issues tracker this issue and there is none

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Tuditi** [comment]
This should be fixed in the new release (https://github.com/iotaledger/firefly/releases/tag/desktop-2.0.1). If the issue still persists try to update your glibc to v. 2.29 (following the steps here: https://www.linuxfromscratch.org/lfs/view/9.0-systemd/chapter05/glibc.html) or to update your ubuntu-18.04 to a newer version (>=19.04) which comes with the correct glibc version.
