### ISSUE TITLE
[Bug report]: Cant claim shimmer rewards, button greyed out

### ISSUE THREAD

**Issue by paco9393** [iotaledger/firefly#4841]
### Platform

Desktop

### Version

FireFly Shimmer v2.0.0

### Description

I can´t claim the Shimmers rewards. The button is not operative to claim. Shimmer balance appears as already claimed.

![Captura 2](https://user-images.githubusercontent.com/115182894/194870536-4f09c298-de22-48e7-8295-f135b33c2f28.JPG)

### Expected behaviour

Claim the rewards

### Actual behaviour

Can´t claim

### Can the issue reliably be reproduced?

Yes

### Steps to reproduce the issue

 Create a new profile with stronghold firefly
Serch for claim rewards

### Operating System

Windows

### Diagnostics

```shell
undefined
```

### Developer Profile

Yes

### Profile Type

Software (Stronghold)

### Staking

Actively staking

### Crash Status

Non-responsive

### Error Messages

undefined

### Error Logs

```shell
undefined
```

### Duplicate declaration

- [X] I have searched the issues tracker this issue and there is none

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by begonaalvarezd** [comment]
@paco9393 if you are trying to claim on a profile that already has SMR funds in it, this view will display those funds as "already claimed" since the funds are already present in your SMR profile. 
If you indeed have unclaimed funds (from the SMR staking period), you can use the button "buscar de nuevo" multiple times until you find your funds and proceed with the normal claiming flow. 
Please re-open this issue if the problem persists.
