### ISSUE TITLE
[Task]: 7. Add logic to update stronghold view

### ISSUE THREAD

**Issue by nicole-obrien** [iotaledger/firefly#6049]
### Task description

Now that we have the UI for updating a stronghold we need to add the logic to perform this action. Involving a call to the [wallet.rs](http://wallet.rs/) to to migrate the stronghold snapshots.

### Requirements

- Add logic to migrate stronghold with [wallet.rs](http://wallet.rs/)
- Add logic to update profile data to state the new version of stronghold for the profile

### Creation checklist

- [x] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project

**Comment by jeeanribeiro** [comment]
Blocked by `error in algorithm XCHACHA20-POLY1305` being thrown when trying to changing password after migration

**Comment by jeeanribeiro** [comment]
Blocked because we had 2 issues that need fixing on wallet.rs side:
- `restoreBackup` is not throwing an error when a v3 stronghold is trying to be restored with an incorrect password.
- `restoreBackup` is throwing a migration required error before throwing an incorrect password error, and this forces us to ask for the password two times if it is incorrect the first time. So for optimal UX flow, we would need the incorrect password error to be thrown first.
