### ISSUE TITLE
Username special characters

### ISSUE THREAD

**Issue by knilch77** [iotaledger/firefly#649]
## Issue description

A username with special characters will freeze the app

## Wallet version

Which version of wallet are you using?

- wallet version (version number, commit, or branch): Version 0.3.0

## System specification

What is your operating system?

Mac/Win/Linux (+Version and or Distro if possible)
Firefly v0.3.0
Plattform: win32
Plattformversion: 10.0.19042
Plattform-Architektur: x64
CPU-Anzahl: 12
Gesamtspeicher: 32679.7 MB
Freier Speicher: 21246.3 MB
Benutzerpfad: C:\Users\ronny\AppData\Roaming\Firefly Beta

## Is it a repeatable issue?

Y

## Steps To reproduce the issue

Explain how the maintainer can reproduce the issue.

1. username with special characters for example <>?
2. Click create new Wallet
3. Back-Button -> Freeze

## Expected behaviour

Not a freeze.
Some information about characters (which are not allowed)

## Errors

Paste any errors that you see from the Error Log in the Firefly menu or share screenshots of the issue.

**Comment by c4chaosiota** [comment]
btw, i think i found a minor bug. nothing crucial. but it could show up for some dumb users like me😎 

when I initially set up my Firefly wallet i included a special character in my profile name: ~C4Chaos (with tilde character). i was able to go through the set up process until I get to the Stronghold portion where I need to save it. i’m NOT ABLE to save! I keep getting the message “something wrong happened”. I tried multiple times but same issue! 

so I tried to set up my wallet from scratch and use a profile name without the special (~) character. that worked! so i suspect that the issue was due to special character in the profile name.

so try it out. in any case, Firely is awesome!

**Comment by Phyloiota** [comment]
Can confirm the behaviour - see screen recording:

can process in clicking create wallet - backbutton - whitefreeze

This error in console:

index.js:2 Uncaught (in promise) TypeError: Cannot read property 'split' of undefined
    at e.exports (index.js:2)
    at index.js:2
    at gt (index.js:2)
    at ft (index.js:2)
    at $t (index.js:2)
    at index.js:2
    at Generator.next (<anonymous>)
    at s (index.js:2)


https://user-images.githubusercontent.com/77154511/112143769-4d0e9280-8c13-11eb-8ab1-ffd2337d9648.mp4

**Comment by obany** [comment]
This is fixes in the next release please re-open if you still have issues.
