### ISSUE TITLE
[Task]: Allow entering a ledger even though the ledger is not connected

### ISSUE THREAD

**Issue by begonaalvarezd** [iotaledger/firefly#7536]
### Task description

At the moment, ledger users cant enter their profiles if the ledger isnot connected, we should allow them

### Requirements

Allow entering a ledger even though the ledger is not connected

### Creation checklist

- [X] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project

**Comment by begonaalvarezd** [comment]
@cpl121 lets try to reproduce this issue and if it is not really a problem lets close it, i can enter without my ledger

**Comment by cpl121** [comment]
@begonaalvarezd I have not been able to reproduce the error and I do not understand what could be happening 🙏🏼

**Comment by cpl121** [comment]
It should be fixed with this [PR](https://github.com/iotaledger/firefly/pull/7623)
I have reproduced the error as described in the PR
![Screenshot 2023-10-19 at 14 24 31](https://github.com/iotaledger/firefly/assets/100352899/f18f777d-7628-44cf-bd77-8785e4291dfc)
and it is fixed
![Screenshot 2023-10-19 at 14 18 57](https://github.com/iotaledger/firefly/assets/100352899/474075bb-3533-4b9b-bec0-0c5780106094)
@begonaalvarezd Do we close the issue, or do we leave it blocked until we verify that it is resolved for the users?
