### ISSUE TITLE
Airdrop

### ISSUE THREAD

**Issue by bunyamin21** [iotaledger/firefly#7541]
### Task description

İyi Akşamlar.
İOTA Shimmer ve Assembly airdroplarına katılmıştım güncelleme yaptım hepsi kayboldu.
mail: orhankarademir21@gmail.com

### Requirements

İyi Akşamlar.
İOTA Shimmer ve Assembly airdroplarına katılmıştım güncelleme yaptım hepsi kayboldu.

mail: orhankarademir21@gmail.com

### Creation checklist

- [ ] I have assigned this task to the correct people
- [ ] I have added the most appropriate labels
- [ ] I have linked the correct milestone and/or project

**Comment by begonaalvarezd** [comment]
Hi, please download the latest Firefly IOTA version 2.0.2. The network was recently upgraded so the old firefly doesnt work anymore
- Assembly: please read https://blog.iota.org/stardust-upgrade-iota-tokenomics/. The assembly project does not exist anymore, but your rewards got airdropped to you in form of IOTAs. They will appear in the new version 2.0.2 in the vesting tab. If you are missing balances you can run the balance finder from settings > advanced > balance finder, or if you are missing rewards you can also run the rewards finder from the vesting tab, the '....' menu, search vesting rewards
- Shimmer: what the old firefly version displayed was just a representation of what you owned, but they were not the real shimmers. You must download the firefly shimmer app to control those funds, you can read more about it here https://blog.shimmer.network/how-to-claim-smr-firefly/

Will close the issue because the new firefly app is not intended to display old staking rewards, but the new iota airdrop and the shimmer tokens should be managed from the shimmer app. 

Please let us know if you have any other issues
