### ISSUE TITLE
Shimmer Guthaben weg

### ISSUE THREAD

**Issue by Tilokoehler** [iotaledger/firefly#7616]
### Version

neuestes heute 18.10.2023

### Description

Mein shimmer Guthaben ist nach der Aktualisierung Firefly weg - wo ist es ?

tilo-koehler@t-online.de

### Expected behaviour

shimmer weg

### Actual behaviour

shimmer weg

### Can the issue reliably be reproduced?

Yes

### Steps to reproduce the issue

shimmer weg

### Operating System

Mac

### Diagnostics

```shell
shimmer weg
```

### Developer Profile

No

### Profile Type

Software (Stronghold)

### Staking

None

### Crash Status

None of the above

### Error Messages

kein

### Error Logs

```shell
Guthaben shimmer weg
```

### Duplicate declaration

- [X] I have searched the issues tracker this issue and there is none

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by begonaalvarezd** [comment]
Quick information about SMR: what the old firefly version displayed was just a representation of what you owned, but they were not the real shimmers. You must download the firefly shimmer app to control those funds, you can read more about it here https://blog.shimmer.network/how-to-claim-smr-firefly/

Will close the issue because the new firefly app is not intended to display old staking rewards, but the shimmer tokens should be managed from the shimmer app. 

Please let us know if you have any other issues
