### ISSUE TITLE
[Bug report]: 

### ISSUE THREAD

**Issue by Vshon** [iotaledger/firefly#7654]
### Version

2.0.2

### Description

Where are ir my tokens shimmer?

### Expected behaviour

my tokens shimmer

### Actual behaviour

no tokens shimmer

### Can the issue reliably be reproduced?

Yes

### Steps to reproduce the issue

come back my tokens of staking shimmer

### Operating System

Windows

### Diagnostics

```shell
where are my tokens shimmer?
```

### Developer Profile

No

### Profile Type

Software (Stronghold)

### Staking

Previously staked

### Crash Status

None of the above

### Error Messages

no

### Duplicate declaration

- [X] I have searched the issues tracker this issue and there is none

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by begonaalvarezd** [comment]
Quick information about SMR: what the old firefly version displayed was just a representation of what you owned, but you couldnt control the shimmers from the iota app. You must download the firefly shimmer app to control those funds, you can read more about it here https://blog.shimmer.network/how-to-claim-smr-firefly/

Will close the issue because the new firefly app is not intended to display old staking rewards, but the shimmer tokens should be managed from the shimmer app. 

Please let us know if you have any other issues
