### ISSUE TITLE
[Task]: Wo sind die Shimmer Torken

### ISSUE THREAD

**Issue by Grobi123** [iotaledger/firefly#7699]
### Task description

Hallo,
in meiner Firefly Wallet werden die Shimmer Torken nicht mehr angezeigr

**Comment by begonaalvarezd** [comment]
Quick information about SMR: what the old firefly version displayed was just a representation of what you owned, but you couldnt control the shimmers from the iota app. You must download the firefly shimmer app to control those funds, you can read more about it here https://blog.shimmer.network/how-to-claim-smr-firefly/

Will close the issue because the new firefly app is not intended to display old staking rewards, but the shimmer tokens should be managed from the shimmer app. 

Please let us know if you have any other issues
