### ISSUE TITLE
[Task]: Fehlende Shimmer Torken

### ISSUE THREAD

**Issue by Grobi123** [iotaledger/firefly#7701]
### Task description

Seit dem Update sind Meine Shimmer Torken verschwunden auf der Iota Firefly und auch auf der Shimmer Firefly nicht mehr auffindbar

**Comment by begonaalvarezd** [comment]
Quick information about SMR: what the old firefly version displayed was just a representation of what you owned, but you couldnt control the shimmers from the iota app. You must download the firefly shimmer app to control those funds, you can read more about it here https://blog.shimmer.network/how-to-claim-smr-firefly/

Will close the issue because the new firefly app is not intended to display old staking rewards, but the shimmer tokens should be managed from the shimmer app. 

Please let us know if you have any other issues
