### ISSUE TITLE
assembly tokens

### ISSUE THREAD

**Issue by ferhatdurup** [iotaledger/firefly#7772]
### Task description

I cannot see the assembly tokens in my account.

**Comment by begonaalvarezd** [comment]
Quick information about ASMB: please read https://blog.iota.org/stardust-upgrade-iota-tokenomics/. The assembly project does not exist anymore, but your rewards got airdropped to you in form of IOTAs. They will appear in the new version 2.0.3 in the vesting tab. If you are missing balances you can run the balance finder from settings > advanced > balance finder, or if you are missing rewards you can also run the rewards finder from the vesting tab, the '....' menu, search vesting rewards

Will close the issue because the new firefly app is not intended to display old staking rewards, but the new iota airdrop is on the new app. 

Please let us know if you have any other issues
