### ISSUE TITLE
[Task]: SMR zurück erhalten

### ISSUE THREAD

**Issue by DanielD83** [iotaledger/firefly#7786]
### Task description

Guten Tag,

nach meinem Wallet Update sind meine via Staking erworbenen SMR alle verloren gegangen. Selbst häufiges suchen in der Wallet mit der Suchfunktion führt zu keinem Ergebnis. Auch der Versuch mit Stronghold Backup etwas zu erreichen ist gescheitert.

Bitte helfen Sie mir bei der Wiederherstellung.

Mit freundlichen Grüßen 
Daniel Doerner

**Comment by DanielD83** [comment]
Thank you. I had the Shimmer App and followed the instructions. My SMR are still gone. Why is there no German support? For Amateurs the App is to complicated.

**Comment by begonaalvarezd** [comment]
> Thank you. I had the Shimmer App and followed the instructions. My SMR are still gone. Why is there no German support? For Amateurs the App is to complicated.

Github is not a support channel, if you need further support you can join our discord https://discord.iota.org/

About your rewards not showing up, it can be because you staked with addresses that have high indexes, which can take multiple searches to find, I suggest you keep pressing the search button until your rewards appear, please make sure you use the same mnemonic/stronghold/ledger you used to stake in the firefly iota app to be able to find your rewards 🙏🏼
