### ISSUE TITLE
Imcomplete transaction history

### ISSUE THREAD

**Issue by KruemelmonsterK** [iotaledger/firefly#7798]
### Version

2.0.4

### Description

Hey guys

when I check for my transaction history in the wallet with the latest version. The history ends with the latest updated of the wallet. Is this a bug? How can I get the complete transaction history?

### Expected behaviour

Complete list of transactions.

### Actual behaviour

List with the transactions since the latest update.

### Can the issue reliably be reproduced?

Yes

### Operating System

Windows

### Developer Profile

No

### Profile Type

Software (Stronghold)

### Staking

Previously staked

### Crash Status

None of the above

### Duplicate declaration

- [X] I have searched the issues tracker this issue and there is none

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by begonaalvarezd** [comment]
The wallet is not intended to hold the full transaction history because it uses normal nodes which do pruning. If you want to check your transaction history you should use the explorer. 
- Stardust (post merge October 4 2023): https://explorer.iota.org/mainnet
- Chrysalis (pre merge): https://explorer.iota.org/chrysalis-mainnet
