### ISSUE TITLE
[Bug report]: Firefly does not show any incoming or outgoing transactions.

### ISSUE THREAD

**Issue by achim-heiniger** [iotaledger/firefly#7912]
### Version

2.0.4

### Description

Sent transaction to bitpanda on january 5th.
Since then, transaction history is gone in wallet, only locked vesting rewards are shown, but no incoming/outgoin value txs. This specific tx is still shown on the mainnet explorer.

But for a transaction done on 27th of october, the tx id can't be found in the wallet, nor in the explorer:
0x9284fe9e053c118404917a2bc6d5b7ef9a482f54de29ae3181ba67e8014cf5a4
Destination address can be found though:
iota1qrq3py8y0y9ey363hp6fkh23aswharhjve40w7ps4f5m5fg3aprfu7nqkhq

### Expected behaviour

Firefly should show all recent incoming and outgoing transactions.

### Actual behaviour

Firefly does not show any incoming or outgoing transactions.

### Can the issue reliably be reproduced?

Yes

### Operating System

Windows

### Developer Profile

No

### Profile Type

Hardware (Ledger)

### Staking

Previously staked

### Crash Status

None of the above

### Error Logs

```shell
Fri, 19 Jan 2024 15:43:57 GMT
wallet: `node error: error sending request for url (https://mainnet-node.tanglebay.com/api/core/v2/transactions/0xb191c4bc825ac6983789e50545d5ef07a1d293a98ad974fc9498cb1876121200/included-block): operation timed out`
```

### Duplicate declaration

- [X] I have searched the issues tracker this issue and there is none

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by begonaalvarezd** [comment]
You can check for the accurate transaction history in the explorer, we recently released some fixes in the explorer and now all your transactions should be visible there eg https://explorer.iota.org/mainnet/transaction/0x9284fe9e053c118404917a2bc6d5b7ef9a482f54de29ae3181ba67e8014cf5a4. You can also see your transaction history in the explorer https://explorer.iota.org/mainnet/addr/iota1qzgcthy8zvnfndg8efgrnuhm2z4n0xeuu86unuyer8cufqjqjykakpnrqyv and we will release an improved tx history so that is in CSV format
