### ISSUE TITLE
Installation of FireFly: Error occurs when trying to create "stronghold file" or trying to skip over it. 

### ISSUE THREAD

**Issue by TheMirror99** [iotaledger/firefly#800]
## Issue description
It is not possible to complete my installation of the FireFly Wallet (Beta) as I neither can create a Stronghold backup nor is it possible for my to skip over it. (see attachted image)

## Wallet version
FireFly Bety 0.3.1

## System specification
I am using a Desktop PC

What is your operating system?
Windows 10 Pro

## Is it a repeatable issue?
Yes

## Steps To reproduce the issue
Explain how the maintainer can reproduce the issue.

1. Download FireFly and start the Installation
2. Get the recovery phrase
3. Confirm recovery phrase
4. Try to Backup your configuration in a "Strong Hold file" or try to skip over this step
==> Here the problem occurs

## Additional Information
There is also no Entry in the "errorlog" created.
When I try to open the Errorlog via: _Menue --> FireFly Bety --> Error Log_ 
I get the message: _Error protocol --> The errorprotocol is empty._

![Error_image](https://user-images.githubusercontent.com/81846418/113469932-bc755500-9451-11eb-9de2-998df6c4ec9f.jpg)

**Comment by Phyloiota** [comment]
Hey - it is a known issue that will be fixed in the next update i think. You can try to enter the wallet with "Backup ueberspringen" and create a wallet like this and do a later backup. This has worked for some users on windows. Also it sometimes works if you just restart the wallet and try again. Another solution is to deinstall the firefly app and do a new installation while running the app "as administrator". You can get help in the discord "Firefly discussion" channel also and we can try to get the wallet working for you

**Comment by netraptor86** [comment]
I had the same issue, I did a workaround using the recovery phrase words created during the first process of create a new wallet to use the import wallet option, then the wallet had been created, I have been able to save backup seed file.

**Comment by obany** [comment]
Could you try with the latest release https://github.com/iotaledger/firefly/releases/tag/desktop-0.4.0 and see if this is still an issue
