### ISSUE TITLE
Iota staking button in the new firefly wallet V2.0.8 is missing

### ISSUE THREAD

**Issue by Hansolo919** [iotaledger/firefly#8137]
### Task description

I just downloaded the new firefly wallet V2.0.8, but the staking button is missing.

**Comment by begonaalvarezd** [comment]
There are no more staking events, that is why there is no more staking button. Here is some information about the previous staking rewards

Quick information about ASMB and SMR:

- Assembly: please read https://blog.iota.org/stardust-upgrade-iota-tokenomics/. The assembly project does not exist anymore, but your rewards got airdropped to you in form of IOTAs. They will appear in the new version in the vesting tab. If you are missing balances you can run the balance finder from settings > advanced > balance finder, or if you are missing rewards you can also run the rewards finder from the vesting tab, the '....' menu, search vesting rewards
- Shimmer: what the old firefly version displayed was just a representation of what you owned, but you couldnt control the shimmers from the iota app because your rewards are in the shimmer network, not the iota network. You must download the firefly shimmer and claim your rewards, you can read more about it here https://blog.shimmer.network/how-to-claim-smr-firefly/
